import blurMap from "./blur-map.json";

const MAP = blurMap as Record<string, string>;

/**
 * Spread onto a next/image `<Image>` to fade a real blurred preview in while
 * the full image loads, instead of holding an empty slot.
 *
 *   <Image src={src} alt="…" fill sizes="50vw" {...blurProps(src)} />
 *
 * The map is keyed by public URL path and generated by `npm run blurmap`
 * (scripts/generate-blur-map.mjs). Unknown/remote src returns no props, so the
 * image simply renders without a placeholder rather than throwing — a missing
 * entry degrades, it never breaks the page.
 *
 * Note: this pulls in blur-map.json (~8KB gzipped). Prefer calling it from
 * server components; it is only worth the client bundle cost where the image
 * is actually above the fold.
 */
export function blurProps(
  src: string,
): { placeholder: "blur"; blurDataURL: string } | Record<string, never> {
  const blurDataURL = MAP[src];
  return blurDataURL ? { placeholder: "blur", blurDataURL } : {};
}
